// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.19.4
// source: gserver/invoke/api/register.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRegisterRouterRegisterRouter = "/invoke.RegisterRouter/RegisterRouter"

type RegisterRouterHTTPServer interface {
	RegisterRouter(context.Context, *RegisterRouterReq) (*RegisterRouterResp, error)
}

func RegisterRegisterRouterHTTPServer(s *http.Server, srv RegisterRouterHTTPServer) {
	r := s.Route("/")
	r.GET("/app/register_router", _RegisterRouter_RegisterRouter0_HTTP_Handler(srv))
}

func _RegisterRouter_RegisterRouter0_HTTP_Handler(srv RegisterRouterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterRouterReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRegisterRouterRegisterRouter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterRouter(ctx, req.(*RegisterRouterReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterRouterResp)
		return ctx.Result(200, reply)
	}
}

type RegisterRouterHTTPClient interface {
	RegisterRouter(ctx context.Context, req *RegisterRouterReq, opts ...http.CallOption) (rsp *RegisterRouterResp, err error)
}

type RegisterRouterHTTPClientImpl struct {
	cc *http.Client
}

func NewRegisterRouterHTTPClient(client *http.Client) RegisterRouterHTTPClient {
	return &RegisterRouterHTTPClientImpl{client}
}

func (c *RegisterRouterHTTPClientImpl) RegisterRouter(ctx context.Context, in *RegisterRouterReq, opts ...http.CallOption) (*RegisterRouterResp, error) {
	var out RegisterRouterResp
	pattern := "/app/register_router"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRegisterRouterRegisterRouter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
