// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: gserver/invoke/api/router.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvokeRouter_Invoke_FullMethodName = "/invoke.InvokeRouter/Invoke"
)

// InvokeRouterClient is the client API for InvokeRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvokeRouterClient interface {
	Invoke(ctx context.Context, in *InvokeReq, opts ...grpc.CallOption) (*InvokeResp, error)
}

type invokeRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewInvokeRouterClient(cc grpc.ClientConnInterface) InvokeRouterClient {
	return &invokeRouterClient{cc}
}

func (c *invokeRouterClient) Invoke(ctx context.Context, in *InvokeReq, opts ...grpc.CallOption) (*InvokeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResp)
	err := c.cc.Invoke(ctx, InvokeRouter_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvokeRouterServer is the server API for InvokeRouter service.
// All implementations must embed UnimplementedInvokeRouterServer
// for forward compatibility.
type InvokeRouterServer interface {
	Invoke(context.Context, *InvokeReq) (*InvokeResp, error)
	mustEmbedUnimplementedInvokeRouterServer()
}

// UnimplementedInvokeRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvokeRouterServer struct{}

func (UnimplementedInvokeRouterServer) Invoke(context.Context, *InvokeReq) (*InvokeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInvokeRouterServer) mustEmbedUnimplementedInvokeRouterServer() {}
func (UnimplementedInvokeRouterServer) testEmbeddedByValue()                      {}

// UnsafeInvokeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvokeRouterServer will
// result in compilation errors.
type UnsafeInvokeRouterServer interface {
	mustEmbedUnimplementedInvokeRouterServer()
}

func RegisterInvokeRouterServer(s grpc.ServiceRegistrar, srv InvokeRouterServer) {
	// If the following call pancis, it indicates UnimplementedInvokeRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvokeRouter_ServiceDesc, srv)
}

func _InvokeRouter_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokeRouterServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvokeRouter_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokeRouterServer).Invoke(ctx, req.(*InvokeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InvokeRouter_ServiceDesc is the grpc.ServiceDesc for InvokeRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvokeRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoke.InvokeRouter",
	HandlerType: (*InvokeRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _InvokeRouter_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gserver/invoke/api/router.proto",
}
