// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: gserver/invoke/api/router.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     uint32                 `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MethodId      uint32                 `protobuf:"varint,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // 建议使用 JSON 字符串（简单易处理）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRequest) Reset() {
	*x = GenericRequest{}
	mi := &file_gserver_invoke_api_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRequest) ProtoMessage() {}

func (x *GenericRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gserver_invoke_api_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRequest.ProtoReflect.Descriptor instead.
func (*GenericRequest) Descriptor() ([]byte, []int) {
	return file_gserver_invoke_api_router_proto_rawDescGZIP(), []int{0}
}

func (x *GenericRequest) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *GenericRequest) GetMethodId() uint32 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *GenericRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GenericRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // 返回的 JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_gserver_invoke_api_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gserver_invoke_api_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_gserver_invoke_api_router_proto_rawDescGZIP(), []int{1}
}

func (x *GenericResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenericResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_gserver_invoke_api_router_proto protoreflect.FileDescriptor

const file_gserver_invoke_api_router_proto_rawDesc = "" +
	"\n" +
	"\x1fgserver/invoke/api/router.proto\x12\x03api\"\xe7\x01\n" +
	"\x0eGenericRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\rR\tserviceId\x12\x1b\n" +
	"\tmethod_id\x18\x02 \x01(\rR\bmethodId\x12:\n" +
	"\aheaders\x18\x03 \x03(\v2 .api.GenericRequest.HeadersEntryR\aheaders\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x0fGenericResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson2E\n" +
	"\x0eInternalRouter\x123\n" +
	"\x06Invoke\x12\x13.api.GenericRequest\x1a\x14.api.GenericResponseB/Z-github.com/zusux/gokit/gserver/invoke/api;apib\x06proto3"

var (
	file_gserver_invoke_api_router_proto_rawDescOnce sync.Once
	file_gserver_invoke_api_router_proto_rawDescData []byte
)

func file_gserver_invoke_api_router_proto_rawDescGZIP() []byte {
	file_gserver_invoke_api_router_proto_rawDescOnce.Do(func() {
		file_gserver_invoke_api_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gserver_invoke_api_router_proto_rawDesc), len(file_gserver_invoke_api_router_proto_rawDesc)))
	})
	return file_gserver_invoke_api_router_proto_rawDescData
}

var file_gserver_invoke_api_router_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gserver_invoke_api_router_proto_goTypes = []any{
	(*GenericRequest)(nil),  // 0: api.GenericRequest
	(*GenericResponse)(nil), // 1: api.GenericResponse
	nil,                     // 2: api.GenericRequest.HeadersEntry
}
var file_gserver_invoke_api_router_proto_depIdxs = []int32{
	2, // 0: api.GenericRequest.headers:type_name -> api.GenericRequest.HeadersEntry
	0, // 1: api.InternalRouter.Invoke:input_type -> api.GenericRequest
	1, // 2: api.InternalRouter.Invoke:output_type -> api.GenericResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gserver_invoke_api_router_proto_init() }
func file_gserver_invoke_api_router_proto_init() {
	if File_gserver_invoke_api_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gserver_invoke_api_router_proto_rawDesc), len(file_gserver_invoke_api_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gserver_invoke_api_router_proto_goTypes,
		DependencyIndexes: file_gserver_invoke_api_router_proto_depIdxs,
		MessageInfos:      file_gserver_invoke_api_router_proto_msgTypes,
	}.Build()
	File_gserver_invoke_api_router_proto = out.File
	file_gserver_invoke_api_router_proto_goTypes = nil
	file_gserver_invoke_api_router_proto_depIdxs = nil
}
