// Code generated by protoc-gen-tag. DO NOT EDIT.
package api

type InvokeReqTag struct {
	ServiceId   uint32            `json:"service_id,omitempty"`
	MethodId    uint32            `json:"method_id,omitempty"`
	Headers     map[string]string `json:"headers,omitempty"`
	PayloadJson string            `json:"payload_json,omitempty"`
}

func (x *InvokeReq) ToInvokeReqTag() *InvokeReqTag {
	if x == nil {
		return nil
	}
	return &InvokeReqTag{
		ServiceId:   x.ServiceId,
		MethodId:    x.MethodId,
		Headers:     x.Headers,
		PayloadJson: x.PayloadJson,
	}
}
func (x *InvokeReqTag) ToInvokeReq() *InvokeReq {
	if x == nil {
		return nil
	}
	return &InvokeReq{
		ServiceId:   x.ServiceId,
		MethodId:    x.MethodId,
		Headers:     x.Headers,
		PayloadJson: x.PayloadJson,
	}
}

type InvokeRespTag struct {
	Code        int32  `json:"code,omitempty"`
	Message     string `json:"message,omitempty"`
	PayloadJson string `json:"payload_json,omitempty"`
}

func (x *InvokeResp) ToInvokeRespTag() *InvokeRespTag {
	if x == nil {
		return nil
	}
	return &InvokeRespTag{
		Code:        x.Code,
		Message:     x.Message,
		PayloadJson: x.PayloadJson,
	}
}
func (x *InvokeRespTag) ToInvokeResp() *InvokeResp {
	if x == nil {
		return nil
	}
	return &InvokeResp{
		Code:        x.Code,
		Message:     x.Message,
		PayloadJson: x.PayloadJson,
	}
}
