// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: gen/protoc-gen-tag/example/user.proto

package example

import (
	_ "github.com/zusux/gokit/gen/protoc-gen-tag/tag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gen_protoc_gen_tag_example_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gen_protoc_gen_tag_example_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gen_protoc_gen_tag_example_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_gen_protoc_gen_tag_example_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_gen_protoc_gen_tag_example_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_gen_protoc_gen_tag_example_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserList) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *UserList              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resp) Reset() {
	*x = Resp{}
	mi := &file_gen_protoc_gen_tag_example_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_gen_protoc_gen_tag_example_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_gen_protoc_gen_tag_example_user_proto_rawDescGZIP(), []int{2}
}

func (x *Resp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Resp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Resp) GetData() *UserList {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gen_protoc_gen_tag_example_user_proto protoreflect.FileDescriptor

const file_gen_protoc_gen_tag_example_user_proto_rawDesc = "" +
	"\n" +
	"%gen/protoc-gen-tag/example/user.proto\x12\auser.v1\x1a\x13zusux/tag/tag.proto\"q\n" +
	"\x04User\x12*\n" +
	"\x02id\x18\x01 \x01(\tB\x1a\xca\xf3\x18\x02id\xd2\xf3\x18\x03_id\xe2\xf3\x18\tcolumn:idR\x02id\x12+\n" +
	"\x04name\x18\x02 \x01(\tB\x17\xca\xf3\x18\x04name\xe2\xf3\x18\vcolumn:nameR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\"C\n" +
	"\bUserList\x127\n" +
	"\x05users\x18\x01 \x03(\v2\r.user.v1.UserB\x12\xca\xf3\x18\x05users\xd2\xf3\x18\x05usersR\x05users\"g\n" +
	"\x04resp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x129\n" +
	"\x04data\x18\x03 \x01(\v2\x11.user.v1.UserListB\x12\xca\xf3\x18\x05users\xd2\xf3\x18\x05usersR\x04dataB$Z\"gen/protoc-gen-tag/example;exampleb\x06proto3"

var (
	file_gen_protoc_gen_tag_example_user_proto_rawDescOnce sync.Once
	file_gen_protoc_gen_tag_example_user_proto_rawDescData []byte
)

func file_gen_protoc_gen_tag_example_user_proto_rawDescGZIP() []byte {
	file_gen_protoc_gen_tag_example_user_proto_rawDescOnce.Do(func() {
		file_gen_protoc_gen_tag_example_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gen_protoc_gen_tag_example_user_proto_rawDesc), len(file_gen_protoc_gen_tag_example_user_proto_rawDesc)))
	})
	return file_gen_protoc_gen_tag_example_user_proto_rawDescData
}

var file_gen_protoc_gen_tag_example_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gen_protoc_gen_tag_example_user_proto_goTypes = []any{
	(*User)(nil),     // 0: user.v1.User
	(*UserList)(nil), // 1: user.v1.UserList
	(*Resp)(nil),     // 2: user.v1.resp
}
var file_gen_protoc_gen_tag_example_user_proto_depIdxs = []int32{
	0, // 0: user.v1.UserList.users:type_name -> user.v1.User
	1, // 1: user.v1.resp.data:type_name -> user.v1.UserList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gen_protoc_gen_tag_example_user_proto_init() }
func file_gen_protoc_gen_tag_example_user_proto_init() {
	if File_gen_protoc_gen_tag_example_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gen_protoc_gen_tag_example_user_proto_rawDesc), len(file_gen_protoc_gen_tag_example_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gen_protoc_gen_tag_example_user_proto_goTypes,
		DependencyIndexes: file_gen_protoc_gen_tag_example_user_proto_depIdxs,
		MessageInfos:      file_gen_protoc_gen_tag_example_user_proto_msgTypes,
	}.Build()
	File_gen_protoc_gen_tag_example_user_proto = out.File
	file_gen_protoc_gen_tag_example_user_proto_goTypes = nil
	file_gen_protoc_gen_tag_example_user_proto_depIdxs = nil
}
