// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: api/user/tag/tag.proto

package tag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_api_user_tag_tag_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51001,
		Name:          "tag.json",
		Tag:           "bytes,51001,opt,name=json",
		Filename:      "api/user/tag/tag.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51002,
		Name:          "tag.bson",
		Tag:           "bytes,51002,opt,name=bson",
		Filename:      "api/user/tag/tag.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51003,
		Name:          "tag.yaml",
		Tag:           "bytes,51003,opt,name=yaml",
		Filename:      "api/user/tag/tag.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51004,
		Name:          "tag.gorm",
		Tag:           "bytes,51004,opt,name=gorm",
		Filename:      "api/user/tag/tag.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string json = 51001;
	E_Json = &file_api_user_tag_tag_proto_extTypes[0]
	// optional string bson = 51002;
	E_Bson = &file_api_user_tag_tag_proto_extTypes[1]
	// optional string yaml = 51003;
	E_Yaml = &file_api_user_tag_tag_proto_extTypes[2]
	// optional string gorm = 51004;
	E_Gorm = &file_api_user_tag_tag_proto_extTypes[3]
)

var File_api_user_tag_tag_proto protoreflect.FileDescriptor

const file_api_user_tag_tag_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/tag/tag.proto\x12\x03tag\x1a google/protobuf/descriptor.proto:3\n" +
	"\x04json\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x8e\x03 \x01(\tR\x04json:3\n" +
	"\x04bson\x12\x1d.google.protobuf.FieldOptions\x18\xba\x8e\x03 \x01(\tR\x04bson:3\n" +
	"\x04yaml\x12\x1d.google.protobuf.FieldOptions\x18\xbb\x8e\x03 \x01(\tR\x04yaml:3\n" +
	"\x04gorm\x12\x1d.google.protobuf.FieldOptions\x18\xbc\x8e\x03 \x01(\tR\x04gormB3Z1github.com/zusux/gokit/gen/protoc-gen-tag/tag;tag"

var file_api_user_tag_tag_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_api_user_tag_tag_proto_depIdxs = []int32{
	0, // 0: tag.json:extendee -> google.protobuf.FieldOptions
	0, // 1: tag.bson:extendee -> google.protobuf.FieldOptions
	0, // 2: tag.yaml:extendee -> google.protobuf.FieldOptions
	0, // 3: tag.gorm:extendee -> google.protobuf.FieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_tag_tag_proto_init() }
func file_api_user_tag_tag_proto_init() {
	if File_api_user_tag_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_tag_tag_proto_rawDesc), len(file_api_user_tag_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_api_user_tag_tag_proto_goTypes,
		DependencyIndexes: file_api_user_tag_tag_proto_depIdxs,
		ExtensionInfos:    file_api_user_tag_tag_proto_extTypes,
	}.Build()
	File_api_user_tag_tag_proto = out.File
	file_api_user_tag_tag_proto_goTypes = nil
	file_api_user_tag_tag_proto_depIdxs = nil
}
