// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: gserver/zrpc/zrpc.proto

package zrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------- HTTP 扩展 -------------------
type HttpRouteOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Get           *string                `protobuf:"bytes,1,opt,name=get" json:"get,omitempty"`
	Post          *string                `protobuf:"bytes,2,opt,name=post" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRouteOptions) Reset() {
	*x = HttpRouteOptions{}
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteOptions) ProtoMessage() {}

func (x *HttpRouteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteOptions.ProtoReflect.Descriptor instead.
func (*HttpRouteOptions) Descriptor() ([]byte, []int) {
	return file_gserver_zrpc_zrpc_proto_rawDescGZIP(), []int{0}
}

func (x *HttpRouteOptions) GetGet() string {
	if x != nil && x.Get != nil {
		return *x.Get
	}
	return ""
}

func (x *HttpRouteOptions) GetPost() string {
	if x != nil && x.Post != nil {
		return *x.Post
	}
	return ""
}

// ------------------- 错误信息 -------------------
type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *string                `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Code          *int32                 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Retry         *bool                  `protobuf:"varint,4,opt,name=retry" json:"retry,omitempty"`
	RetryDelay    *int64                 `protobuf:"varint,5,opt,name=retry_delay,json=retryDelay" json:"retry_delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_gserver_zrpc_zrpc_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorInfo) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ErrorInfo) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ErrorInfo) GetRetry() bool {
	if x != nil && x.Retry != nil {
		return *x.Retry
	}
	return false
}

func (x *ErrorInfo) GetRetryDelay() int64 {
	if x != nil && x.RetryDelay != nil {
		return *x.RetryDelay
	}
	return 0
}

// ------------------- 鉴权信息 -------------------
type CSignKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint32                `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Domain        *string                `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	CompanyId     *uint32                `protobuf:"varint,4,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSignKey) Reset() {
	*x = CSignKey{}
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSignKey) ProtoMessage() {}

func (x *CSignKey) ProtoReflect() protoreflect.Message {
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSignKey.ProtoReflect.Descriptor instead.
func (*CSignKey) Descriptor() ([]byte, []int) {
	return file_gserver_zrpc_zrpc_proto_rawDescGZIP(), []int{2}
}

func (x *CSignKey) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *CSignKey) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *CSignKey) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *CSignKey) GetCompanyId() uint32 {
	if x != nil && x.CompanyId != nil {
		return *x.CompanyId
	}
	return 0
}

// ------------------- 通用头部（精简版） -------------------
type CRpcHead struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginUid       *uint64                `protobuf:"varint,1,opt,name=origin_uid,json=originUid" json:"origin_uid,omitempty"`
	ServiceId       *uint32                `protobuf:"varint,2,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	MethodId        *uint32                `protobuf:"varint,3,opt,name=method_id,json=methodId" json:"method_id,omitempty"`
	ClientLang      *uint32                `protobuf:"varint,4,opt,name=client_lang,json=clientLang" json:"client_lang,omitempty"`
	ClientIpv4      *uint32                `protobuf:"varint,5,opt,name=client_ipv4,json=clientIpv4" json:"client_ipv4,omitempty"`
	DeviceId        *string                `protobuf:"bytes,6,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	TraceId         []byte                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	SpanId          []byte                 `protobuf:"bytes,8,opt,name=span_id,json=spanId" json:"span_id,omitempty"`
	ErrInfo         *ErrorInfo             `protobuf:"bytes,100,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CRpcHead) Reset() {
	*x = CRpcHead{}
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRpcHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRpcHead) ProtoMessage() {}

func (x *CRpcHead) ProtoReflect() protoreflect.Message {
	mi := &file_gserver_zrpc_zrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRpcHead.ProtoReflect.Descriptor instead.
func (*CRpcHead) Descriptor() ([]byte, []int) {
	return file_gserver_zrpc_zrpc_proto_rawDescGZIP(), []int{3}
}

func (x *CRpcHead) GetOriginUid() uint64 {
	if x != nil && x.OriginUid != nil {
		return *x.OriginUid
	}
	return 0
}

func (x *CRpcHead) GetServiceId() uint32 {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return 0
}

func (x *CRpcHead) GetMethodId() uint32 {
	if x != nil && x.MethodId != nil {
		return *x.MethodId
	}
	return 0
}

func (x *CRpcHead) GetClientLang() uint32 {
	if x != nil && x.ClientLang != nil {
		return *x.ClientLang
	}
	return 0
}

func (x *CRpcHead) GetClientIpv4() uint32 {
	if x != nil && x.ClientIpv4 != nil {
		return *x.ClientIpv4
	}
	return 0
}

func (x *CRpcHead) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *CRpcHead) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *CRpcHead) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *CRpcHead) GetErrInfo() *ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

var file_gserver_zrpc_zrpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50001,
		Name:          "zrpc.service_option_id",
		Tag:           "varint,50001,opt,name=service_option_id",
		Filename:      "gserver/zrpc/zrpc.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50002,
		Name:          "zrpc.method_option_id",
		Tag:           "varint,50002,opt,name=method_option_id",
		Filename:      "gserver/zrpc/zrpc.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRouteOptions)(nil),
		Field:         10003,
		Name:          "zrpc.method_option_http_api",
		Tag:           "bytes,10003,opt,name=method_option_http_api",
		Filename:      "gserver/zrpc/zrpc.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional uint32 service_option_id = 50001;
	E_ServiceOptionId = &file_gserver_zrpc_zrpc_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional uint32 method_option_id = 50002;
	E_MethodOptionId = &file_gserver_zrpc_zrpc_proto_extTypes[1]
	// optional zrpc.HttpRouteOptions method_option_http_api = 10003;
	E_MethodOptionHttpApi = &file_gserver_zrpc_zrpc_proto_extTypes[2]
)

var File_gserver_zrpc_zrpc_proto protoreflect.FileDescriptor

const file_gserver_zrpc_zrpc_proto_rawDesc = "" +
	"\n" +
	"\x17gserver/zrpc/zrpc.proto\x12\x04zrpc\x1a google/protobuf/descriptor.proto\"8\n" +
	"\x10HttpRouteOptions\x12\x10\n" +
	"\x03get\x18\x01 \x01(\tR\x03get\x12\x12\n" +
	"\x04post\x18\x02 \x01(\tR\x04post\"\x88\x01\n" +
	"\tErrorInfo\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05retry\x18\x04 \x01(\bR\x05retry\x12\x1f\n" +
	"\vretry_delay\x18\x05 \x01(\x03R\n" +
	"retryDelay\"g\n" +
	"\bCSignKey\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"company_id\x18\x04 \x01(\rR\tcompanyId\"\xac\x02\n" +
	"\bCRpcHead\x12\x1d\n" +
	"\n" +
	"origin_uid\x18\x01 \x01(\x04R\toriginUid\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\rR\tserviceId\x12\x1b\n" +
	"\tmethod_id\x18\x03 \x01(\rR\bmethodId\x12\x1f\n" +
	"\vclient_lang\x18\x04 \x01(\rR\n" +
	"clientLang\x12\x1f\n" +
	"\vclient_ipv4\x18\x05 \x01(\rR\n" +
	"clientIpv4\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\b \x01(\fR\x06spanId\x12*\n" +
	"\berr_info\x18d \x01(\v2\x0f.zrpc.ErrorInfoR\aerrInfo*\x06\b\xe8\a\x10\xd0\x0f:M\n" +
	"\x11service_option_id\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\rR\x0fserviceOptionId:J\n" +
	"\x10method_option_id\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\rR\x0emethodOptionId:l\n" +
	"\x16method_option_http_api\x12\x1e.google.protobuf.MethodOptions\x18\x93N \x01(\v2\x16.zrpc.HttpRouteOptionsR\x13methodOptionHttpApiB*Z(github.com/zusux/gokit/gserver/zrpc;zrpc"

var (
	file_gserver_zrpc_zrpc_proto_rawDescOnce sync.Once
	file_gserver_zrpc_zrpc_proto_rawDescData []byte
)

func file_gserver_zrpc_zrpc_proto_rawDescGZIP() []byte {
	file_gserver_zrpc_zrpc_proto_rawDescOnce.Do(func() {
		file_gserver_zrpc_zrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gserver_zrpc_zrpc_proto_rawDesc), len(file_gserver_zrpc_zrpc_proto_rawDesc)))
	})
	return file_gserver_zrpc_zrpc_proto_rawDescData
}

var file_gserver_zrpc_zrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gserver_zrpc_zrpc_proto_goTypes = []any{
	(*HttpRouteOptions)(nil),            // 0: zrpc.HttpRouteOptions
	(*ErrorInfo)(nil),                   // 1: zrpc.ErrorInfo
	(*CSignKey)(nil),                    // 2: zrpc.CSignKey
	(*CRpcHead)(nil),                    // 3: zrpc.CRpcHead
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 5: google.protobuf.MethodOptions
}
var file_gserver_zrpc_zrpc_proto_depIdxs = []int32{
	1, // 0: zrpc.CRpcHead.err_info:type_name -> zrpc.ErrorInfo
	4, // 1: zrpc.service_option_id:extendee -> google.protobuf.ServiceOptions
	5, // 2: zrpc.method_option_id:extendee -> google.protobuf.MethodOptions
	5, // 3: zrpc.method_option_http_api:extendee -> google.protobuf.MethodOptions
	0, // 4: zrpc.method_option_http_api:type_name -> zrpc.HttpRouteOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gserver_zrpc_zrpc_proto_init() }
func file_gserver_zrpc_zrpc_proto_init() {
	if File_gserver_zrpc_zrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gserver_zrpc_zrpc_proto_rawDesc), len(file_gserver_zrpc_zrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_gserver_zrpc_zrpc_proto_goTypes,
		DependencyIndexes: file_gserver_zrpc_zrpc_proto_depIdxs,
		MessageInfos:      file_gserver_zrpc_zrpc_proto_msgTypes,
		ExtensionInfos:    file_gserver_zrpc_zrpc_proto_extTypes,
	}.Build()
	File_gserver_zrpc_zrpc_proto = out.File
	file_gserver_zrpc_zrpc_proto_goTypes = nil
	file_gserver_zrpc_zrpc_proto_depIdxs = nil
}
